version: '3.8'

services:

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A tasks flower --port=5555
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
